name: build docs
on:
  push:
    branches: [ master ]
    paths:
      - '**.tf'
      - '**.yml'

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: get all tags
      run: git fetch origin +refs/tags/*:refs/tags/*
    - name: build docs
      uses: richardjkendall/tf-auto-document.action@v0.06
      with:
        modulesFolder: 'modules'
    - name: commit doc changes
      run : |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        git add *.md
        git add **/*.md
        git config user.email "richard@rjk.email"
        git config user.name "Robot"
        git commit -m "docs for commit $git_hash"
        git push
